
@token = 1782|v6GLdVEkyVtxsIVOTM1HHa1UJsZYkWLQ0pjQUedB5d4734ca

### Login
POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{
  "email": "pedroyorpo17@gmail.com",
  "password": "Madmin123@"
}

### getAllModules
GET http://127.0.0.1:8000/api/getAllModules
Authorization: Bearer {{token}}
Accept: application/json

### getAllModules
GET http://127.0.0.1:8000/api/menu
Authorization: Bearer {{token}}
Accept: application/json

### get
GET http://127.0.0.1:8000/api/getSubmenuByTransNo/2
Authorization: Bearer {{token}}
Accept: application/json

### getAllPostByFollow
GET http://127.0.0.1:8000/api/getPost
Authorization: Bearer {{token}}
Accept: application/json

# https://lightgreen-pigeon-122992.hostingersite.com/public/api/

